name = "personal-site"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-06-04"

[[d1_databases]]
binding = "DB"
database_name = "personal-site"
database_id = "7080af35-3095-4055-ab59-e86080a09bca"

