name = "personal-website"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-06-04"

[[d1_databases]]
binding = "DB"
database_name = "personal-website"
database_id = "a20d4a63-261b-48a3-bf81-31877bdf4b84"

